// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest      = require("@glennsl/bs-jest/src/jest.js");
var Puppeteer = require("puppeteer");

describe("Expect Puppeteer", (function () {
        Jest.test("Dummy test", (function () {
                return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
              }));
        var puppet = Puppeteer;
        Jest.test("defaultArgs", (function () {
                return Jest.Expect[/* toBe */2](/* array */["headless"], Jest.Expect[/* expect */0](puppet.defaultArgs()));
              }));
        Jest.test("executablePath", (function () {
                return Jest.Expect[/* toBe */2]("chrome", Jest.Expect[/* expect */0](puppet.executablePath()));
              }));
        puppet.launch({ }).then((function (browser) {
                  console.log("got browser");
                  return browser.close();
                })).then((function () {
                console.log("browser closed");
                return Promise.resolve(/* () */0);
              }));
        return /* () */0;
      }));

/*  Not a pure module */
